"use client";
import { QueryClientProvider } from "@tanstack/react-query";
import { motion } from "framer-motion";
import { BookOpen, Video, FileText, Lightbulb } from "lucide-react";
import { queryClient } from "@/lib/tanstack-query/queryClient";
import { AppShell } from "@/components/design-system/organisms/AppShell";
import { GlassCard } from "@/components/design-system/organisms/GlassCard";
import { Badge } from "@/components/design-system/atoms/Badge";

const LEARNING_CONTENT = [
  {
    category: "Beginner",
    icon: Lightbulb,
    courses: [
      {
        title: "Stock Market Basics",
        type: "Course",
        duration: "2 hours",
        lessons: 12,
      },
      {
        title: "Understanding Technical Analysis",
        type: "Video Series",
        duration: "1.5 hours",
        lessons: 8,
      },
    ],
  },
  {
    category: "Intermediate",
    icon: FileText,
    courses: [
      {
        title: "Advanced Chart Patterns",
        type: "Course",
        duration: "3 hours",
        lessons: 15,
      },
      {
        title: "Risk Management Strategies",
        type: "Workshop",
        duration: "2 hours",
        lessons: 10,
      },
    ],
  },
  {
    category: "Advanced",
    icon: Video,
    courses: [
      {
        title: "Algorithmic Trading Strategies",
        type: "Course",
        duration: "4 hours",
        lessons: 20,
      },
      {
        title: "Options Trading Mastery",
        type: "Course",
        duration: "5 hours",
        lessons: 25,
      },
    ],
  },
];

function LearnPage() {
  return (
    <div className="container mx-auto p-6 max-w-6xl space-y-8">
      {/* Header */}
      <motion.div
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        className="text-center py-8"
      >
        <BookOpen className="h-16 w-16 mx-auto mb-4 text-primary" />
        <h1 className="text-4xl font-bold mb-2">Learning Center</h1>
        <p className="text-xl text-muted-foreground">
          Master trading with AI-generated tutorials and expert guides
        </p>
      </motion.div>

      {/* Learning Paths */}
      {LEARNING_CONTENT.map((section, sectionIdx) => {
        const IconComponent = section.icon;
        return (
          <div key={section.category}>
            <div className="flex items-center gap-3 mb-4">
              <IconComponent className="h-6 w-6 text-primary" />
              <h2 className="text-2xl font-bold">{section.category}</h2>
            </div>
            <div className="grid md:grid-cols-2 gap-4">
              {section.courses.map((course, idx) => (
                <motion.div
                  key={course.title}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: sectionIdx * 0.1 + idx * 0.05 }}
                >
                  <GlassCard className="p-6 hover:shadow-xl transition-shadow cursor-pointer">
                    <Badge variant="default" className="mb-3">
                      {course.type}
                    </Badge>
                    <h3 className="text-xl font-bold mb-2">{course.title}</h3>
                    <div className="flex items-center gap-4 text-sm text-muted-foreground">
                      <span>{course.lessons} lessons</span>
                      <span>•</span>
                      <span>{course.duration}</span>
                    </div>
                  </GlassCard>
                </motion.div>
              ))}
            </div>
          </div>
        );
      })}

      {/* AI Tutor Feature */}
      <GlassCard gradient className="p-8 text-center">
        <h2 className="text-2xl font-bold mb-4">🤖 AI Trading Tutor</h2>
        <p className="text-muted-foreground mb-4">
          Get personalized lessons generated by AI based on your trading style and
          experience level
        </p>
        <Badge variant="violet" className="text-sm">
          Coming Soon
        </Badge>
      </GlassCard>
    </div>
  );
}

export default function Learn() {
  return (
    <QueryClientProvider client={queryClient}>
      <AppShell
        topBarContent={null}
        sidebarContent={null}
        alertCount={0}
        userEmail="user@example.com"
      >
        <LearnPage />
      </AppShell>
    </QueryClientProvider>
  );
}

